### PR TITLE
dynamic iOS 13 dark mode

### PR DESCRIPTION
**Pull request by EkilDeew**
Re-opening a PR I opened during the iOS 13 beta.

This will enable dynamic switch of the theme based on the system theme.

I didn't touch the settings side as the `about` branch is doing changes so i'll add the dynamic theme when this is done

Currently enabling or disabling dark mode manually in the settings view will stop the app from automatically switch between system theme until a restart. I don't know what behavior you would expect from the app so i'll wait for your insight.

### CODE REVIEW

**Comment by weiran** [comment]
👍 

There is still a light/dark theme setting in Settings. I think there should be a `System` option at the top, that only shows for iOS 13 or above to trigger this. 

This would also still allow you to override the system theme.

**Comment by EkilDeew** [comment]
So what i've done is I added a switch on top of the dark theme switch. If the system switch is on it will prevent changing the dark / light theme, if its not the dark or light theme will override the system theme.

**Comment by weiran** [comment]
@EkilDeew: I pushed a few commits to your fork that:

- resolved merge conflicts with my latest PR
- changed so all theme colours are derived from the Colors.xcassets file to prevent duplicate definitions

Let me know if you're ok with these changes and I'll be happy to merge the whole PR. 👍 

Thanks!

**Comment by EkilDeew** [comment]
So the only problem I encountered was that by setting `traitCollection` to `UITraitCollection.current` the system theme in the app would be lock to the current one. If the device would change to dark mode the app wouldn't reflect this. I did find a way to fix this which is what I did in the latest commit.

Unfortunately the bug still persists when the system theme toggle is clicked.

**Comment by weiran** [comment]
Great spot, I did a bit of digging and I found it's because the `ThemeSwitcher` class uses   `SettingsStore` which is linked to the hidden SwiftUI version of the settings view. Since adding the new system appearance setting this has broken the logic there. Changing it to look at the right settings and triggering a theme change on a trait collection change has resolved that bug.

**Comment by weiran** [comment]
Big thanks for your help @EkilDeew, I didn't realise how much work it would be for a seemingly trivial setting but here we are! I'll release 4.2 with this in the next week or so.

**Pull request merged**
